### ISSUE TITLE
Impossible to dock a pane in the center pane area

### ISSUE THREAD

**Issue by Kinaou** [nhold/wxWidgets#24]
After having undocked the center pane it is impossible to dock a pane again in the center pane area.

**Comment by ghost** [comment]
This should be fixed by the latest commit.

**Comment by ghost** [comment]
Kinaou, can you check the latest code and tell me if it's ok for you now ?

**Comment by Kinaou** [comment]
With pleasure, I do that during the week

**Comment by mjmacleod** [comment]
Just waiting for your latest pull request to land so that we are all on the same code and then I can try give you an example of when this is still happening.

**Comment by mjmacleod** [comment]
With the latest auidemo sample:
1) Dock top left pane "Movable" over center panes
2) Drag other two center panes away
3) Drag "Movable" pane away
There is now an empty hole that cannot be filled in center.

**Comment by nhold** [comment]
That seems to work for me, however I can still get blank spaces that I can't dock to in my own project, check it out:

https://www.dropbox.com/s/k5bksba4bg5r64d/aa%20%2802%29.webmhd.webm

**Comment by mjmacleod** [comment]
Hrm, you are right it does work now. I guess it matters which panes are/aren't allowed to be center dockable, but then shouldn't the same thing apply for the first drop?
i.e. If the Movable pane is not allowed in the center why are we allowing it to dock over in the center?
We should probably be consistent about this behaviour I guess? Or does it not make sense to enforce such restrictions on dock overs?

**Comment by ghost** [comment]
Well, I asked myself the question, and could not get to an answer, so I let dock over not checking the direction, as I prefer not restricting things without a good reason.
However, if you need to dock panes side by side on the center area or to allow the first drop, the panes need to have the CENTER dock direction. You may also notice that in the center area, side by side docking is only vertical (I don't know if it's a problem, but I don't see how to do otherwise).
If you have still a problem with your project Nathan, try to give me a reduced version of it: I'll check out what's wrong.

**Comment by mjmacleod** [comment]
I don't feel strongly about it, but the one thing is it might be confusing for users if they can drag a pane _out_ of the center, but can't put it back. (As is the case with the Movable pane there)
So from that perspective maybe consistency would be better, however I don't know, perhaps this is something to ask the mailing list. It probably doesn't need to be solved pre-merge, but I'm not sure.

**Comment by nhold** [comment]
I am not sure, it feels like a bug that something was docked somewhere but is now unable to be, although that may be my error so I'll double check my code first.

**Comment by dronesalot** [comment]
There is another related bug in the demo. 

1) Run it. 
2) Close the floatable5 tab. Now you can no longer dock anything on the centre pane.

**Comment by Kinaou** [comment]
It is because of the method `wxAuiPaneInfo::CenterPane()` in `framemanager.h` which resets the attribute `state` to zero (and thus unsets the flag `optionCaption` which sets the caption to visible state defined by default in the `wxAuiPaneInfo` ctor)...

```
wxAuiPaneInfo& CenterPane()
{
    state = 0;
    return Center().PaneBorder().Resizable();
}
```
